# Generated by Django 2.2.5 on 2021-02-21 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=300)),
                ('set_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('FD', 'Food&Drink'), ('HM', 'Home'), ('AT', 'Activities'), ('SR', 'Services'), ('RE', 'Recreation'), ('TR', 'Travel'), ('MI', 'Miscellenius')], default='HM', max_length=2)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('AC', 'Active'), ('NA', 'Not Active')], default='AC', max_length=2)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_by', models.ManyToManyField(related_name='watching', to=settings.AUTH_USER_MODEL)),
                ('watched_item', models.ManyToManyField(related_name='watched', to='auctions.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=500)),
                ('commented_on', models.DateTimeField(auto_now=True)),
                ('comments_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('comments_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_status', models.CharField(choices=[('CL', 'Closed'), ('ON', 'Open')], default='ON', max_length=2)),
                ('bid_time', models.DateTimeField(auto_now=True)),
                ('bid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.Listing')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
