# Generated by Django 2.2.5 on 2021-02-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='set_price',
            new_name='starting_bid',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='item',
            new_name='title',
        ),
    ]
