# Generated by Django 2.2.5 on 2021-02-25 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210222_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watched_by',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watched_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='watched_item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watched_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Listing'),
        ),
    ]
