# Generated by Django 2.2.5 on 2021-02-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210225_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
