# Generated by Django 2.2.5 on 2021-02-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210227_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Home', 'Home'), ('Activities', 'Activities'), ('Services', 'Services'), ('Recreation', 'Recreation'), ('Travel', 'Travel'), ('Miscellenius', 'Miscellenius')], default='Home', max_length=2),
        ),
    ]
